---
title: "Fine-mapping Pipeline"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Welcome to the project website. 

My thesis project is about improving functional fine mapping procedures that enable us to identify causal variants underlying complex traits such as obsesity and asthma. 

# Introduction
This document will provide an overview of my thesis project, including the aims for the project, summary of previous work, details of the method, and preliminary results. By constantly reviewing this document, I can keep track of my research aims without getting diverted too far. 


## Literature reviews 
* [Current challenges in functional fine-mapping]
* [Existing pipelines or methods]
    - Polyfun + SuSiE
    - TORUS + SuSiE
* [Biology backgrounds](biology_bkg.html)
* [Prediction methods](method_bkg.html)

## Results by Methods 
* [feedbacks]
* [Torus enrichment results](enrichment_analysis.html)
* [LDSC enrichment results](ldsc_results.html)
* [fine mapping results](snp_finemapping_results.html)
* [gene mapping results]

## Results by Projects
* [Asthma Projects](asthma_prelim_results.html)
    - [identifying TRMs](identifying_TRMs_in_lungs.html)
    - [scRNA-seq analysis](lung_Wang2020_scRNA.html)
    - [scATAC-seq analysis](exploring_lung_scATAC_R.html)
* [Functional annotation project]
    - [PTR_results](ldsc_PTR_results.html)


## Sample QCs by dataset
* [Wang2020 et al.]


## References
